### ISSUE TITLE
2 x hub12 drive

### ISSUE THREAD

**Issue by trinityworld** [HakkanR/DMD2TUR#4]
have you tried to drive 2 x hub12 parallel data for big fonts?

**Comment by HakkanR** [comment]
no, is there any problem with that?

**Comment by trinityworld** [comment]
no i just want to try with big font but with 2 ports

**Comment by HakkanR** [comment]
I don't think there will be a problem with that, if your project work well with dmd2 then there is no problem with dmd2tur.
