### ISSUE TITLE
How can I add turkish letters to my fonts library?

### ISSUE THREAD

**Issue by mucahitturk** [HakkanR/DMD2TUR#5]
I have a Callibri15.h fonts file. I understand your way to create a new letter in library. I need to add 20 to 31 for turkish letters in .h file.
In addition, I have to add char width. But I do not understand how to calculate the font size in struct.

**Comment by HakkanR** [comment]
I've added a calibri font (Turkish Chars Supported) to the library,
and planned a video on my youtube channel at 30 April 2023, Sunday, 15:00!
you will find all details about creating a new font for DMD2 and adding Turkish letters.

https://youtu.be/k5t7g0ehDJw

**Comment by HakkanR** [comment]
calibri.h font added to library, how to video link is shared.
